global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'signoz-monitor' 
scrape_configs:
  - job_name: 'signoz-service'
    static_configs:
      - targets: ['localhost:8080']   